### ISSUE TITLE
Link to blog not working

### ISSUE THREAD

**Issue by DataExplorerUser** [dmnfarrell/tablexplore#3]
On https://dmnfarrell.github.io/tablexplore/, there is a link to "My Blog", which links to https://dmnfarrell.github.com/. I think that should be dmnfarrell.github.io.

The app looks great, by the way. I used Pandastable before and just found out about Tablexplore, so I'm interested to try Tablexplore now.

**Comment by dmnfarrell** [comment]
Ok thanks. Will fix that.
