### ISSUE TITLE
Graph Zoom-in // Zoom-out odd behaviour

### ISSUE THREAD

**Issue by Goran-L** [dmnfarrell/tablexplore#8]
When you click to Zoom-in // Zoom-out on the top right corner of the graph, it changes the text size, but display doesn't zoom at all.
Is this normal behavior or maybe a bug? Maybe it's just the magnifier glass icon which is misleading.

![CaptureBefore](https://user-images.githubusercontent.com/60929759/168898770-a7f374bf-027a-45d9-8794-a3c7a5ca67fc.JPG)
![CaptureAfterZoomClicks](https://user-images.githubusercontent.com/60929759/168898786-169c0bd8-6f5e-42d1-be5a-903138920896.JPG)

**Comment by dmnfarrell** [comment]
Yes its not zoom really. Those buttons enlarge or reduce the plot elements. Maybe the magnifying glass should be removed. To zoom into sections of the plot use the left controls. You should be able to drag an area to zoom.

**Comment by Goran-L** [comment]
OK, That's waht I thought while writing the message. Yes maybe some other icon would be less missleading. Something like in Office suite for ex:
![image](https://user-images.githubusercontent.com/60929759/169036132-ea297435-57cb-4934-af64-3889146e0771.png)

Thanks for the explanation !

**Comment by dmnfarrell** [comment]
This is changed as per your suggestion.
